config/routes.rb
Rails.application.routes.draw do
  get 'session/new'
  resources :users
  resources :reservations
  resources :planes
  resources :flights
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/plane.rb
class Plane < ApplicationRecord
    has_many :flights
end

app/controllers/planes_controller.rb
class PlanesController < ApplicationController
  before_action :set_plane, only: %i[ show edit update destroy ]

  # GET /planes or /planes.json
  def index
    @planes = Plane.all
  end

  # GET /planes/1 or /planes/1.json
  def show
  end

  # GET /planes/new
  def new
    @plane = Plane.new
  end

  # GET /planes/1/edit
  def edit
  end

  # POST /planes or /planes.json
  def create
    @plane = Plane.new(plane_params)

    respond_to do |format|
      if @plane.save
        format.html { redirect_to plane_url(@plane), notice: "Plane was successfully created." }
        format.json { render :show, status: :created, location: @plane }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @plane.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /planes/1 or /planes/1.json
  def update
    respond_to do |format|
      if @plane.update(plane_params)
        format.html { redirect_to plane_url(@plane), notice: "Plane was successfully updated." }
        format.json { render :show, status: :ok, location: @plane }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @plane.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /planes/1 or /planes/1.json
  def destroy
    @plane.destroy

    respond_to do |format|
      format.html { redirect_to planes_url, notice: "Plane was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plane
      @plane = Plane.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def plane_params
      params.require(:plane).permit(:name, :seat_row, :seat_col)
    end
end

app/helpers/planes_helper.rb
module PlanesHelper
end

app/views/planes/_form.html.erb
<%= form_with(model: plane, local: true) do |form| %>
  <% if plane.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plane.errors.count, "error") %> prohibited this plane from being saved:</h2>

      <ul>
      <% plane.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name %>
  </div>

  <div class="field">
    <%= form.label :seat_row %>
    <%= form.text_area :seat_row %>
  </div>

  <div class="field">
    <%= form.label :seat_col %>
    <%= form.text_area :seat_col %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/planes/edit.html.erb
<h1>Editing Plane</h1>

<%= render 'form', plane: @plane %>

<%= link_to 'Show', @plane %> |
<%= link_to 'Back', planes_path %>

app/views/planes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Planes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Seat row</th>
      <th>Seat col</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @planes.each do |plane| %>
      <tr>
        <td><%= plane.name %></td>
        <td><%= plane.seat_row %></td>
        <td><%= plane.seat_col %></td>
        <td><%= link_to 'Show', plane %></td>
        <td><%= link_to 'Edit', edit_plane_path(plane) %></td>
        <td><%= link_to 'Destroy', plane, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plane', new_plane_path %>

app/views/planes/new.html.erb
<h1>New Plane</h1>

<%= render 'form', plane: @plane %>

<%= link_to 'Back', planes_path %>

app/views/planes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @plane.name %>
</p>

<p>
  <strong>Seat row:</strong>
  <%= @plane.seat_row %>
</p>

<p>
  <strong>Seat col:</strong>
  <%= @plane.seat_col %>
</p>

<%= link_to 'Edit', edit_plane_path(@plane) %> |
<%= link_to 'Back', planes_path %>